services:
  db:
    image: postgres:17
    container_name: mentor_mentee_db
    restart: always
    ports:
      - "5430:5432" 
    env_file:
      - ./backend/FastAPI for login and mentor profile/.env
    volumes:
      - mentor_mentee_pg_data:/var/lib/postgresql/data
    networks:
      - mentor_mentee_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  backend:
    build: "./backend/FastAPI for login and mentor profile"
    env_file:
      - ./backend/FastAPI for login and mentor profile/.env
    container_name: mentor_mentee_backend
    restart: always
    ports:
      - "8080:8000" 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - mentor_mentee_network

  frontend:
    build: ./frontend_web
    env_file:
      - .env
    container_name: mentor_mentee_frontend
    restart: always
    ports:
      - "8081:80" 
    networks:
      - mentor_mentee_network

networks:
  mentor_mentee_network:
    name: mentor_mentee_network
    external: true

volumes:
  mentor_mentee_pg_data:
