"""Initial migration

Revision ID: 3fc8fc052259
Revises: 
Create Date: 2025-04-17 11:13:42.546934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc8fc052259'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentee_course_id', table_name='mentee_course')
    op.drop_table('mentee_course')
    op.drop_index('ix_course_id', table_name='course')
    op.drop_table('course')
    op.alter_column('roadmap', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmap', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('course_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name='course_domain_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='course_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_course_id', 'course', ['id'], unique=False)
    op.create_table('mentee_course',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mentee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='mentee_course_course_id_fkey'),
    sa.ForeignKeyConstraint(['mentee_id'], ['user.id'], name='mentee_course_mentee_id_fkey'),
    sa.ForeignKeyConstraint(['mentor_id'], ['user.id'], name='mentee_course_mentor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mentee_course_pkey')
    )
    op.create_index('ix_mentee_course_id', 'mentee_course', ['id'], unique=False)
    # ### end Alembic commands ###
