"""Recreate missing migration

Revision ID: 462ae529abda
Revises: 
Create Date: 2025-04-21 12:36:35.868300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462ae529abda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.add_column('mentee_skill', sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', name='proficiencylevel'), nullable=True))
    op.add_column('topic', sa.Column('subtopic_durations', sa.Text(), nullable=True))
    op.add_column('topic', sa.Column('topic_duration_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'topic_duration_days')
    op.drop_column('topic', 'subtopic_durations')
    op.drop_column('mentee_skill', 'proficiency')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'topic_id')
    # ### end Alembic commands ###
