"""Updated topic and roadmap table

Revision ID: 5930453bd9d5
Revises: 3fc8fc052259
Create Date: 2025-04-17 11:17:31.149545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5930453bd9d5'
down_revision: Union[str, None] = '3fc8fc052259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('topic', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('topic', sa.Column('subtopics', sa.Text(), nullable=True))
    op.add_column('topic', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'reasoning')
    op.drop_column('topic', 'subtopics')
    op.drop_column('topic', 'description')
    op.drop_column('roadmap', 'description')
    # ### end Alembic commands ###
